resolver: nightly-2017-09-14

ghc-options:
  "*": -fwarn-unused-binds -fwarn-unused-matches -fwarn-unused-imports -fno-warn-simplifiable-class-constraints

packages:
  - src/ast
  - src/backend-ghc
  - src/rewrite
  - src/prettyprint
  - src/refactor
  - src/builtin-refactorings
  - src/experimental-refactorings
  - demo
  - src/cli
  - src/debug
  - src/daemon

extra-deps:
  - fswatch-0.1.0.2
  - knob-0.1.1
