resolver: lts-7.7

packages:
  - src/ast
  - src/backend-ghc
  - src/rewrite
  - src/prettyprint
  - src/refactor

# Dependency packages to be pulled from upstream that are not in the resolver
extra-deps: 
  - references-0.3.2.0
  - instance-control-0.1.1.1
