resolver: lts-8.20

packages:
  - src/ast
  - src/backend-ghc
  - src/rewrite
  - src/prettyprint
  - src/refactor
  - demo
  - src/cli
  - src/debug
  - src/daemon
  - location: https://github.com/kelemzol/watch/archive/master.zip
    extra-dep: true
