resolver: lts-9.0

ghc-options:
  "*": -fwarn-unused-binds -fwarn-unused-matches -fwarn-unused-imports

packages:
  - src/ast
  - src/backend-ghc
  - src/rewrite
  - src/prettyprint
  - src/refactor
  - src/builtin-refactorings
  - src/experimental-refactorings
  - demo
  - src/cli
  - src/debug
  - src/daemon

extra-deps:
- fswatch-0.1.0.1
